In [2]:
import numpy as np

In [26]:
# create vector  (array 1D)

a = np.array((1, 2, 3))
a = np.array([1, 2, 3])

print(a)

b = np.arange(1, 10, 2)
c = np.linspace(1, 8, 3)

print(b)
print(c)


[1 2 3]
[1 3 5 7 9]
[1.  4.5 8. ]


In [27]:
# create matrix (array 2D)

d = np.array([ (1, 2, 3), 
               (4, 4, 5),
               (8, 9, 11) ])

print(d)
print(d.ndim)
print(d.shape)

dd = d.dot(d)
print(dd)

[[ 1  2  3]
 [ 4  4  5]
 [ 8  9 11]]
2
(3, 3)
[[ 33  37  46]
 [ 60  69  87]
 [132 151 190]]


In [28]:
# access matrix

print(d[0])
print(d[0][1])

[1 2 3]
2


In [29]:
# create multiple matrix (array 3D)

nMatrix = np.array(
    [
        [
        (1, 2, 3), 
        (4, 5, 6), 
        (7, 8, 9)
        ],

        [
        (1, 2, 3), 
        (4, 5, 6), 
        (7, 8, 9)
        ]
              
    ])

print(nMatrix)
print(nMatrix.ndim)
print(nMatrix.shape)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(2, 3, 3)


In [30]:
# create 4D array

arr4D = np.array(
[
    [
        [[1, 2, 3],
         [4, 5, 6]],

        [[6, 7, 8],
         [9, 10, 11]]
    ],

    [
        [[1, 2, 3],
         [4, 5, 6]],

        [[6, 7, 8],
         [9, 10, 11]]
    ]

])

print(arr4D)
print(arr4D.ndim)
print(arr4D.shape)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 6  7  8]
   [ 9 10 11]]]]
4
(2, 2, 2, 3)


In [8]:
# create array using arange

arr = np.arange(24).reshape(4, 3, 2)
print("\narr 3D \n ",arr)

re_arr = arr.reshape(4,2,3)
print("\narr 3D reshape \n",re_arr)



arr 3D 
  [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

arr 3D reshape 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [31]:
# access index from array 3D

m = nMatrix[0]
m_row = nMatrix[0][1]
m_row_col = nMatrix[0][1][2]

print(m)
print(m_row)
print(m_row_col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6


In [10]:
# matrix with values = 0

f = np.zeros([5, 5])

print(f)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# matrix with values = 1

g = np.ones((4, 5))

print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
# matrix identity

h = np.identity(5)

print(h)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
# matrix identity

i = np.eye(5)

print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# Looping in Arr 3D

for i in range(len(nMatrix)):
    print(f"matrix {i} = \n {nMatrix[i]}")
    for row in range(len(nMatrix[i])):
        print(f"\t matrix {i} row {row} = {nMatrix[i][row]}")
        for column in range(len(nMatrix[i][row])):
             print(f"\t\t matrix {i} row {row} col {column} = {nMatrix[i][row][column]}")


matrix 0 = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
	 matrix 0 row 0 = [1 2 3]
		 matrix 0 row 0 col 0 = 1
		 matrix 0 row 0 col 1 = 2
		 matrix 0 row 0 col 2 = 3
	 matrix 0 row 1 = [4 5 6]
		 matrix 0 row 1 col 0 = 4
		 matrix 0 row 1 col 1 = 5
		 matrix 0 row 1 col 2 = 6
	 matrix 0 row 2 = [7 8 9]
		 matrix 0 row 2 col 0 = 7
		 matrix 0 row 2 col 1 = 8
		 matrix 0 row 2 col 2 = 9
matrix 1 = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
	 matrix 1 row 0 = [1 2 3]
		 matrix 1 row 0 col 0 = 1
		 matrix 1 row 0 col 1 = 2
		 matrix 1 row 0 col 2 = 3
	 matrix 1 row 1 = [4 5 6]
		 matrix 1 row 1 col 0 = 4
		 matrix 1 row 1 col 1 = 5
		 matrix 1 row 1 col 2 = 6
	 matrix 1 row 2 = [7 8 9]
		 matrix 1 row 2 col 0 = 7
		 matrix 1 row 2 col 1 = 8
		 matrix 1 row 2 col 2 = 9
